* Added make_db command * Fixed bug where cleanup branch code was not in helper function

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -46,6 +46,7 @@ usage() {
 	echo "       git flow feature start [-F] <name> [<base>]"
 	echo "       git flow feature finish [-rFkD] [<name|nameprefix>]"
 	echo "       git flow feature publish <name>"
+	echo "       git flow feature make_db 	#in case you realized too late you needed a database"
 	echo "       git flow feature track <name>"
 	echo "       git flow feature diff [<name|nameprefix>]"
 	echo "       git flow feature rebase [-i] [<name|nameprefix>]"
@@ -347,6 +348,15 @@ cmd_start() {
 	echo
 }
 
+cmd_make_db() {
+	parse_args "$@"
+	expand_nameprefix_arg_or_current
+
+	BRANCH_DB_NAME=$(get_db_name_from_branch $BRANCH);
+	make_db $BRANCH_DB_NAME
+	make_sql_file $BRANCH_DB_NAME
+}
+
 cmd_finish() {
 	DEFINE_boolean fetch true "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean rebase false "rebase instead of merge" r
@@ -467,24 +477,6 @@ cmd_finish() {
 	# when no merge conflict is detected, just clean up the feature branch
 	helper_finish_cleanup
 
-	#source sql on database
-	BRANCH_DB_NAME=$(get_db_name_from_branch $BRANCH);
-	sqlFileName=sql/$BRANCH_DB_NAME.sql
-	if [ -f $sqlFileName ]; then
-		echo "Sourcing $sqlFileName on master...";
-		source_sql_on_db "$sqlFileName" 'master';
-	fi
-	echo "Dropping database...{$BRANCH_DB_NAME}";
-	drop_db_if_exists $BRANCH_DB_NAME;
-	
-	#push BASE (master) to origin
-	if ! git push "$ORIGIN" "$DEVELOP_BRANCH:refs/heads/$DEVELOP_BRANCH"; then
-		warn "Pushing to origin FAILED!  Please run :"
-		warn "	git pull --rebase;"
-		warn "  git push $ORIGIN $DEVELOP_BRANCH:refs/heads/$DEVELOP_BRANCH"
-		exit 1
-	fi
-	echo "'$DEVELOP_BRANCH' pushed to $ORIGIN"
 	exit;
 }
 
@@ -518,6 +510,25 @@ helper_finish_cleanup() {
 	fi
 	echo "- You are now on branch '$DEVELOP_BRANCH'"
 	echo
+	
+	#source sql on database
+	BRANCH_DB_NAME=$(get_db_name_from_branch $BRANCH);
+	sqlFileName=sql/$BRANCH_DB_NAME.sql
+	if [ -f $sqlFileName ]; then
+		echo "Sourcing $sqlFileName on master...";
+		source_sql_on_db "$sqlFileName" 'master';
+	fi
+	echo "Dropping database...{$BRANCH_DB_NAME}";
+	drop_db_if_exists $BRANCH_DB_NAME;
+	
+	#push BASE (master) to origin
+	if ! git push "$ORIGIN" "$DEVELOP_BRANCH:refs/heads/$DEVELOP_BRANCH"; then
+		warn "Pushing to origin FAILED!  Please run :"
+		warn "	git pull --rebase;"
+		warn "  git push $ORIGIN $DEVELOP_BRANCH:refs/heads/$DEVELOP_BRANCH"
+		exit 1
+	fi
+	echo "'$DEVELOP_BRANCH' pushed to $ORIGIN"
 }
 
 cmd_publish() {
